### ISSUE TITLE
Falsche Datenbank verwendet wenn die Definition der Klasse-Attribute abgeholt werden

### ISSUE THREAD

**Issue by BartekOchab** [infopark/reactor#20]
Man nehme eine frische Rails App mit den folgenden Gems
```
gem 'rails', '4.1.9'
gem 'sqlite3'
gem 'mysql2'
gem 'infopark_fiona_connector','6.10.0.beta1'
gem 'infopark_reactor','1.12.0.beta2' # '1.12.0.beta2'
```
Darin definieren wir die folgenden beiden Klassen:
```ruby
class Obj < RailsConnector::BasicObj
  include Reactor::Main
end
```

```ruby
class Folder < Obj
end
```
Folder entspricht hierbei einer Vorlage im CMS. Weiter sagen wir dass für development und cms unterschiedliche Datenbanken verwendet werden sollen:
```yml
…
development:
 adapter: mysql2
 database: development
 username: developmentuser
 password: developmentuser
…
cms:
  adapter: mysql2
  database: 610cm
  username: 610cmuser
  password: 610cmuser
…
```
Anschließend versuchen wir uns ein Objekt aus dem CMS zu holen:

```irb
$ rails c
Loading development environment (Rails 4.1.9)
irb(main):001:0> f = Folder.find(10039)
  RailsConnector::ObjClass Load (48.6ms)  SELECT `support_obj_classes`.* FROM `support_obj_classes`
  RailsConnector::Attribute Load (47.2ms)  SELECT `support_attributes`.* FROM `support_attributes` INNER JOIN `support_obj_class_attrs` ON `support_attributes`.`attribute_id` = `support_obj_class_attrs`.`attribute_id` WHERE `support_obj_class_attrs`.`obj_class_id` = 2003
  RailsConnector::Attribute Load (47.2ms)  SELECT `support_attributes`.* FROM `support_attributes` INNER JOIN `support_obj_class_attrs` ON `support_attributes`.`attribute_id` = `support_obj_class_attrs`.`attribute_id` WHERE `support_obj_class_attrs`.`obj_class_id` = 2004
  RailsConnector::Attribute Load (47.6ms)  SELECT `support_attributes`.* FROM `support_attributes` INNER JOIN `support_obj_class_attrs` ON `support_attributes`.`attribute_id` = `support_obj_class_attrs`.`attribute_id` WHERE `support_obj_class_attrs`.`obj_class_id` = 2005
  RailsConnector::Attribute Load (48.2ms)  SELECT `support_attributes`.* FROM `support_attributes` INNER JOIN `support_obj_class_attrs` ON `support_attributes`.`attribute_id` = `support_obj_class_attrs`.`attribute_id` WHERE `support_obj_class_attrs`.`obj_class_id` = 2006
  RailsConnector::Attribute Load (50.2ms)  SELECT `support_attributes`.* FROM `support_attributes` INNER JOIN `support_obj_class_attrs` ON `support_attributes`.`attribute_id` = `support_obj_class_attrs`.`attribute_id` WHERE `support_obj_class_attrs`.`obj_class_id` = 2007
  RailsConnector::Attribute Load (47.6ms)  SELECT `support_attributes`.* FROM `support_attributes` INNER JOIN `support_obj_class_attrs` ON `support_attributes`.`attribute_id` = `support_obj_class_attrs`.`attribute_id` WHERE `support_obj_class_attrs`.`obj_class_id` = 2008
  RailsConnector::Attribute Load (47.1ms)  SELECT `support_attributes`.* FROM `support_attributes` INNER JOIN `support_obj_class_attrs` ON `support_attributes`.`attribute_id` = `support_obj_class_attrs`.`attribute_id` WHERE `support_obj_class_attrs`.`obj_class_id` = 2009
  RailsConnector::Attribute Load (48.9ms)  SELECT `support_attributes`.* FROM `support_attributes` INNER JOIN `support_obj_class_attrs` ON `support_attributes`.`attribute_id` = `support_obj_class_attrs`.`attribute_id` WHERE `support_obj_class_attrs`.`obj_class_id` = 2090
  RailsConnector::Attribute Load (48.3ms)  SELECT `support_attributes`.* FROM `support_attributes` INNER JOIN `support_obj_class_attrs` ON `support_attributes`.`attribute_id` = `support_obj_class_attrs`.`attribute_id` WHERE `support_obj_class_attrs`.`obj_class_id` = 25934
  RailsConnector::ObjClass Load (48.2ms)  SELECT `support_obj_classes`.* FROM `support_obj_classes`
Mysql2::Error: Table 'development.support_obj_class_attrs' doesn't exist: SHOW FULL FIELDS FROM `support_obj_class_attrs`
ActiveRecord::StatementInvalid: Mysql2::Error: Table 'development.support_obj_class_attrs' doesn't exist: SHOW FULL FIELDS FROM `support_obj_class_attrs`
	from /Users/bartek/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `query'
	from /Users/bartek/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `block in execute'
	from /Users/bartek/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract_adapter.rb:373:in `block in log'
	from /Users/bartek/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.9/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
	from /Users/bartek/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract_adapter.rb:367:in `log'
	from /Users/bartek/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `execute'
	from /Users/bartek/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/mysql2_adapter.rb:228:in `execute'
	from /Users/bartek/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:310:in `execute_and_free'
	from /Users/bartek/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:451:in `columns'
	from /Users/bartek/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/schema_cache.rb:93:in `block in prepare_default_proc'
	from /Users/bartek/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/schema_cache.rb:44:in `yield'
	from /Users/bartek/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/schema_cache.rb:44:in `columns'
	from /Users/bartek/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.9/lib/active_record/model_schema.rb:214:in `columns'
	from /Users/bartek/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.9/lib/active_record/model_schema.rb:223:in `columns_hash'
	from /Users/bartek/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.9/lib/active_record/model_schema.rb:227:in `column_types'
	from /Users/bartek/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.9/lib/active_record/associations/preloader/association.rb:107:in `association_key_type'
... 46 levels...
	from /Users/bartek/Projects/link_title_bug/app/models/folder.rb:1:in `<top (required)>'
	from /Users/bartek/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:443:in `load'
	from /Users/bartek/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:443:in `block in load_file'
	from /Users/bartek/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:633:in `new_constants_in'
	from /Users/bartek/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:442:in `load_file'
	from /Users/bartek/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:342:in `require_or_load'
	from /Users/bartek/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:480:in `load_missing_constant'
	from /Users/bartek/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:180:in `const_missing'
	from (irb):1
	from /Users/bartek/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.1.9/lib/rails/commands/console.rb:90:in `start'
	from /Users/bartek/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.1.9/lib/rails/commands/console.rb:9:in `start'
	from /Users/bartek/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.1.9/lib/rails/commands/commands_tasks.rb:69:in `console'
	from /Users/bartek/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.1.9/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /Users/bartek/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.1.9/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by tomaszp-infopark** [comment]
Gelöst b1eb45a9d4a421e51c469e5ebb0656165892e5ee
